# -*- coding: utf-8 -*-
# Lanches e cafés PARA PREPARAR ANTES E LEVAR.
# port      = dá para fazer antes e transportar (pode pedir bolsa térmica)
# port_seco = aguenta o dia fora da geladeira, sem esquentar nada
# Ingredientes sempre da TACO; instruções escritas aqui.

LANCHES = [
# ---------------------------------------------- frutas e mix (sem preparo)
("lv_mix_castanhas","Mix de castanhas e amendoim",["lanche","ceia"],
 [("castanha_caju",15),("castanha_para",10),("amendoim",15)],
 "Monte porções em saquinhos no domingo. Dura a semana toda na gaveta.",5),
("lv_banana_castanha","Banana e castanha de caju",["lanche","ceia"],
 [("banana",100),("castanha_caju",20)],"A banana viaja bem se for firme.",1),
("lv_maca_amendoa","Maçã e amêndoas",["lanche","ceia"],
 [("maca",130),("amendoa",20)],"Não precisa de gelo nem de nada.",1),
("lv_pera_castanha","Pera e castanha-do-pará",["lanche","ceia"],
 [("pera",150),("castanha_para",12)],"Duas castanhas bastam.",1),
("lv_tangerina_amendoim","Tangerina e amendoim torrado",["lanche","ceia"],
 [("tangerina",150),("amendoim",20)],"Fácil de descascar sem sujeira.",1),
("lv_uva_amendoa","Uva e amêndoas",["lanche","ceia"],
 [("uva",120),("amendoa",18)],"Lave e seque as uvas antes de guardar.",3),
("lv_mexerica_castanha","Mexerica e castanhas",["lanche","ceia"],
 [("mexerica",150),("castanha_caju",18)],"Combinação de bolso.",1),
("lv_banana_passa_aveia","Banana com aveia e mel em pote",["lanche","ceia"],
 [("banana",110),("aveia",30),("mel",10)],"Monte no pote de véspera; regue com limão para não escurecer.",5),
("lv_salada_frutas_pote","Salada de frutas no pote",["lanche","cafe","ceia"],
 [("mamao",110),("maca",90),("banana",70),("laranja",90)],
 "Corte tudo e cubra com o suco da laranja — segura a cor e o gosto.",10),
("lv_frutas_coco","Frutas picadas com coco e linhaça",["lanche","ceia"],
 [("manga",130),("abacaxi",100),("coco",12),("linhaca",8)],
 "Coco e linhaça em potinho separado, para não umedecer.",8),
("lv_goiaba_castanha","Goiaba e castanhas",["lanche","ceia"],
 [("goiaba",150),("castanha_caju",18)],"Goiaba inteira aguanta a mochila.",1),
("lv_caqui_amendoa","Caqui e amêndoas",["lanche","ceia"],
 [("caqui",150),("amendoa",15)],"Escolha o caqui firme para levar.",1),
("lv_ameixa_noz","Ameixa e castanhas",["lanche","ceia"],
 [("ameixa",120),("castanha_para",12)],"Ajuda quem tem intestino preguiçoso.",1),
("lv_melao_castanha","Melão em cubos com castanhas",["lanche","ceia"],
 [("melao",200),("castanha_caju",15)],"Melão em pote fechado, gelado de casa.",6),
("lv_abacaxi_hortela","Abacaxi em cubos",["lanche","ceia"],
 [("abacaxi",180)],"Corte e guarde com um pouco do próprio caldo.",6),

# ---------------------------------------------- potes montados na véspera
("lv_pote_iogurte_aveia","Pote de iogurte com aveia e banana",["lanche","cafe","ceia"],
 [("iogurte",170),("aveia",30),("banana",80)],
 "Camadas no pote com tampa: iogurte, aveia, fruta. Monte à noite.",5),
("lv_pote_iogurte_morango","Pote de iogurte com morango e granola de aveia",["lanche","cafe"],
 [("iogurte_desnatado",170),("morango",90),("aveia",30),("mel",8)],
 "Aveia por último, para não amolecer antes da hora.",5),
("lv_overnight_oats","Aveia da noite anterior com leite e cacau",["lanche","cafe"],
 [("aveia",50),("leite",180),("cacau",6),("banana",70)],
 "Misture tudo no pote e deixe na geladeira. De manhã é só pegar.",5),
("lv_overnight_soja","Aveia da noite anterior com bebida de soja",["lanche","cafe"],
 [("aveia",50),("leite_soja",180),("linhaca",10),("banana",70)],
 "Versão vegana do pote de aveia.",5),
("lv_pote_chia_manga","Pote de linhaça com manga e iogurte",["lanche","ceia"],
 [("linhaca",15),("manga",140),("iogurte",140)],
 "A linhaça hidratada engrossa e sacia mais.",5),
("lv_pote_acai","Pote de açaí com banana e aveia",["lanche","cafe"],
 [("acai",140),("banana",80),("aveia",25)],
 "Congele o pote; ele descongela até a hora do lanche.",6),
("lv_pote_ricota_fruta","Pote de ricota com mel e fruta",["lanche","ceia"],
 [("ricota",80),("mel",10),("morango",80)],"Ricota amassada com o mel, fruta por cima.",5),
("lv_pote_cottage_tomate","Pote de ricota com tomate e azeite",["lanche"],
 [("ricota",90),("tomate",80),("azeite",6)],"Versão salgada do pote, boa para quem enjoa de doce.",5),
("lv_pote_leite_fermentado","Leite fermentado com mamão",["lanche","ceia"],
 [("leite_fermentado",180),("mamao",140)],"Leve o mamão picado à parte.",4),
("lv_pote_frutas_iogurte","Pote de iogurte com salada de frutas",["lanche","ceia"],
 [("iogurte",150),("mamao",90),("banana",60),("maca",70)],"Monte na véspera, com limão nas frutas.",8),
("lv_pote_grao_legumes","Pote de grão-de-bico com tomate e pepino",["lanche","jantar"],
 [("grao_de_bico",110),("tomate",70),("pepino",60),("azeite",8),("limao",8)],
 "Salada de pote: molho no fundo, grão no meio, folhas em cima.",12),
("lv_pote_lentilha","Pote de lentilha com cenoura e azeite",["lanche","jantar"],
 [("lentilha",130),("cenoura_crua",60),("azeite",8),("limao",8)],"Vegano e aguenta o dia na bolsa térmica.",25),

# ---------------------------------------------- sanduíches e wraps
("lv_sand_frango","Sanduíche natural de frango desfiado",["lanche","cafe"],
 [("pao_integral",50),("frango_desfiado",70),("cenoura_crua",40),("alface",20)],
 "Frango temperado com iogurte no lugar da maionese. Embrulhe em papel-filme.",12),
("lv_sand_atum","Sanduíche natural de atum",["lanche"],
 [("pao_integral",50),("atum_lata",70),("tomate",40),("alface",20)],
 "Atum bem escorrido, senão o pão umedece.",10),
("lv_sand_ovo","Sanduíche de ovo com cenoura",["lanche","cafe"],
 [("pao_integral",50),("ovo_cozido",100),("cenoura_crua",40)],
 "Ovo amassado com um fio de azeite, sal e cebolinha.",12),
("lv_sand_peru","Sanduíche de peito de peru com queijo",["lanche"],
 [("pao_integral",50),("peru",40),("queijo_prato",25),("alface",20)],"Monte de manhã, come à tarde.",6),
("lv_sand_ricota_cenoura","Sanduíche de ricota com cenoura",["lanche"],
 [("pao_integral",50),("ricota",60),("cenoura_crua",50)],"Pasta de ricota com cheiro-verde.",8),
("lv_sand_abacate_ovo","Sanduíche de abacate com ovo",["lanche","cafe"],
 [("pao_aveia",50),("abacate",60),("ovo_cozido",50),("limao",8)],
 "Limão no abacate segura a cor até a tarde.",10),
("lv_sand_sardinha","Sanduíche de pasta de sardinha",["lanche"],
 [("pao_integral",50),("sardinha_lata",60),("limao",8),("alface",20)],
 "Sardinha amassada com limão e cebolinha.",8),
("lv_sand_presunto_queijo","Sanduíche de presunto magro e queijo minas",["lanche"],
 [("pao_frances",50),("presunto",35),("queijo_minas",35),("tomate",30)],"O clássico do lanche.",6),
("lv_wrap_frango_abacate","Wrap de frango com abacate",["lanche","jantar"],
 [("pao_integral",60),("frango_desfiado",80),("abacate",50),("rucula",25)],
 "Enrole apertado no papel-filme e corte ao meio.",12),
("lv_wrap_atum","Wrap de atum com cenoura",["lanche","jantar"],
 [("pao_integral",60),("atum_lata",70),("cenoura_crua",50),("alface",25)],"Aguenta bem 6 horas na bolsa.",10),
("lv_wrap_ricota_legumes","Wrap de ricota com legumes",["lanche","jantar"],
 [("pao_integral",60),("ricota",70),("cenoura_crua",40),("pepino",50)],"Vegetariano e leve.",10),
("lv_sand_pao_queijo_peru","Pão de queijo com peito de peru",["lanche"],
 [("pao_queijo",70),("peru",35)],"Asse no domingo e congele; leve já assado.",25),
("lv_torrada_pasta_grao","Torradas com pasta de grão-de-bico",["lanche"],
 [("torrada",30),("grao_de_bico",90),("azeite",8),("limao",8)],
 "Homus em pote e as torradas separadas, para não amolecer.",15),
("lv_cracker_queijo","Cream cracker com queijo minas",["lanche"],
 [("cream_cracker",30),("queijo_minas",45)],"Queijo em pote com tampa, biscoito no pacote.",3),
("lv_cracker_pasta_atum","Cream cracker com pasta de atum",["lanche"],
 [("cream_cracker",30),("atum_lata",70),("limao",8)],"Pasta em potinho, biscoito à parte.",8),

# ---------------------------------------------- assados: bolos e panquecas
("lv_bolo_banana_aveia","Bolo de banana com aveia",["lanche","cafe"],
 [("banana",120),("aveia",50),("ovo_frito",50),("mel",10),("linhaca",8)],
 "Bata tudo, asse 30 min a 180 °C e corte em pedaços para a semana.",40),
("lv_bolo_cenoura_cacau","Bolo de cenoura com cacau",["lanche","cafe"],
 [("cenoura_crua",90),("farinha_trigo",60),("ovo_frito",50),("oleo",10),("cacau",8)],
 "Bata a cenoura crua com o ovo e o óleo antes de juntar a farinha.",45),
("lv_bolo_fuba","Bolo de fubá",["lanche","cafe"],
 [("farinha_milho",70),("leite",80),("ovo_frito",45),("oleo",10)],
 "Bolo de liquidificador, o mais barato da lista.",45),
("lv_bolo_caneca_cacau","Bolo de caneca de cacau e aveia",["lanche","ceia"],
 [("aveia",40),("cacau",8),("ovo_frito",50),("leite",60),("mel",10)],
 "Três minutos no micro-ondas. Faça na véspera e leve na própria caneca fechada.",6),
("lv_bolo_caneca_banana","Bolo de caneca de banana",["lanche","ceia"],
 [("banana",90),("aveia",35),("ovo_frito",50),("canjica",0),("mel",8)],
 "Amasse a banana, junte ovo e aveia, 3 min no micro-ondas.",6),
("lv_panqueca_aveia","Panquecas de aveia e banana para levar",["lanche","cafe"],
 [("aveia",45),("banana",100),("ovo_frito",55)],
 "Faça uma leva no domingo; empilhe com papel entre elas e congele.",25),
("lv_panqueca_proteica","Panquecas de aveia com clara de ovo",["lanche","cafe"],
 [("aveia",45),("clara",90),("banana",80),("cacau",6)],
 "Mais proteína e menos gordura usando só as claras.",25),
("lv_crepioca_fria","Crepioca fria de queijo",["lanche","cafe"],
 [("tapioca",30),("ovo_frito",55),("queijo_minas",40)],
 "Faça de manhã, enrole e leve. Fica boa fria.",10),
("lv_muffin_legumes","Muffin salgado de legumes",["lanche","cafe"],
 [("farinha_trigo",50),("ovo_frito",55),("leite",60),("cenoura_crua",50),("queijo_prato",25)],
 "Forminhas de muffin, 25 min a 180 °C. Congela bem.",40),
("lv_muffin_frango","Muffin salgado de frango",["lanche"],
 [("farinha_trigo",50),("ovo_frito",50),("leite",60),("frango_desfiado",60)],
 "Mesma massa do muffin de legumes, com frango no lugar.",40),
("lv_bolinho_arroz_assado","Bolinho de arroz assado",["lanche","jantar"],
 [("bolinho_arroz",120)],"Assado em vez de frito, ótimo destino para o arroz de ontem.",30),
("lv_bolinho_batata_doce","Bolinho de batata-doce com aveia",["lanche","cafe"],
 [("batata_doce",140),("aveia",35),("ovo_frito",45),("coco",10)],
 "Amasse a batata-doce cozida, misture e asse em bolinhas.",40),
("lv_pao_caseiro_queijo","Pão de queijo caseiro",["lanche","cafe"],
 [("pao_queijo",80)],"Congele crus e asse a quantidade do dia.",25),
("lv_biscoito_polvilho","Biscoito de polvilho com queijo",["lanche"],
 [("tapioca",40),("queijo_minas",30),("ovo_frito",30)],
 "Sem glúten, aguenta dias em pote fechado.",40),
("lv_bolo_integral_maca","Bolo integral de maçã",["lanche","cafe"],
 [("maca",100),("farinha_trigo",60),("ovo_frito",45),("aveia",25),("mel",10)],
 "Maçã ralada com casca deixa o bolo úmido sem precisar de muito óleo.",45),

# ---------------------------------------------- salgados assados
("lv_quiche_espinafre","Quiche de espinafre e ricota",["lanche","jantar"],
 [("farinha_trigo",45),("ovo_frito",55),("espinafre",70),("ricota",60),("leite",50)],
 "Corte em fatias e leve fria, fica ótima.",50),
("lv_quiche_atum","Quiche de atum e tomate",["lanche","jantar"],
 [("farinha_trigo",45),("ovo_frito",55),("atum_lata",70),("tomate",60)],
 "Uma forma rende a semana inteira de lanches.",50),
("lv_torta_frango","Torta de frango de liquidificador",["lanche","jantar"],
 [("farinha_trigo",55),("ovo_frito",50),("leite",80),("frango_desfiado",90),("oleo",10)],
 "Bata os líquidos, metade da massa, recheio, resto da massa. 35 min.",50),
("lv_torta_legumes","Torta de legumes de liquidificador",["lanche","jantar"],
 [("farinha_trigo",55),("ovo_frito",50),("leite",80),("cenoura",60),("vagem",60)],
 "Vegetariana, boa fria no dia seguinte.",50),
("lv_tortilha_batata","Tortilha espanhola de batata e ovo",["lanche","jantar","cafe"],
 [("batata",160),("ovo_frito",110),("cebola",40),("azeite",10)],
 "Fria em fatias é um dos melhores lanches para levar.",35),
("lv_omelete_forno","Omelete de forno com legumes",["lanche","jantar","cafe"],
 [("ovo_frito",110),("abobrinha",70),("tomate",60),("queijo_prato",25)],
 "Asse numa forma, corte em quadrados e guarde em pote.",30),
("lv_quibe_assado","Quibe assado com castanha",["lanche","jantar"],
 [("quibe",140),("castanha_para",10)],"Corte em quadrados; fica bom frio.",50),
("lv_esfiha_frango","Esfiha aberta de frango",["lanche"],
 [("farinha_trigo",60),("frango_desfiado",70),("cebola",30),("azeite",8)],
 "Massa simples de trigo; asse e congele.",60),
("lv_empadinha_frango","Empadinha de frango",["lanche"],
 [("farinha_trigo",55),("manteiga",15),("frango_desfiado",70)],
 "Faz uma fornada e congela; assa a quantidade da semana.",60),
("lv_pastel_forno","Pastel de forno de queijo",["lanche"],
 [("farinha_trigo",60),("queijo_minas",45),("ovo_frito",25)],"Assado, não frito.",50),
("lv_falafel","Falafel assado de grão-de-bico",["lanche","jantar"],
 [("grao_de_bico",130),("cebola",30),("azeite",10),("salsa",10)],
 "Grão cru de molho na véspera, batido e assado. Vegano.",45),
("lv_crispy_grao","Grão-de-bico crocante temperado",["lanche","ceia"],
 [("grao_de_bico",90),("azeite",8)],
 "Cozido, seco no pano e assado 25 min a 200 °C com páprica. Dura dias em pote.",35),

# ---------------------------------------------- proteínas prontas
("lv_ovos_cozidos","Ovos cozidos para a semana",["lanche","cafe","ceia"],
 [("ovo_cozido",100)],"Cozinhe uma dúzia no domingo e guarde com casca na geladeira.",12),
("lv_ovos_codorna","Ovos de codorna em pote",["lanche","ceia"],
 [("ovo_codorna",90)],"Cozidos e descascados, em pote com água e sal.",15),
("lv_ovo_abacate_pote","Ovo cozido com abacate em pote",["lanche"],
 [("ovo_cozido",100),("abacate",70),("limao",8)],"Abacate com limão não escurece até a tarde.",10),
("lv_frango_desfiado_pote","Frango desfiado temperado em pote",["lanche","jantar"],
 [("frango_desfiado",110),("cenoura_crua",50),("azeite",6)],
 "Cozinhe e desfie o peito no domingo; rende vários lanches.",35),
("lv_atum_pote","Atum com milho e tomate em pote",["lanche","jantar"],
 [("atum_lata",80),("milho_verde",70),("tomate",60),("azeite",6)],"Só abrir e comer.",6),
("lv_sardinha_pote","Sardinha com limão em pote",["lanche"],
 [("sardinha_lata",90),("limao",10),("cebola",30)],"Barata e cheia de ômega-3.",5),
("lv_peru_queijo_rolinho","Rolinhos de peito de peru com queijo",["lanche","ceia"],
 [("peru",50),("queijo_prato",30)],"Enrole o queijo na fatia de peru. Zero preparo.",3),
("lv_tremoco_pote","Tremoço em pote",["lanche","ceia"],
 [("tremoco",130),("limao",8)],"Vegano, proteico e barato. Vem pronto do mercado.",2),
("lv_grao_ovo_pote","Grão-de-bico com ovo picado",["lanche","jantar"],
 [("grao_de_bico",110),("ovo_cozido",100),("tomate",60),("azeite",8)],"Lanche que segura até o jantar.",15),
("lv_queijo_azeitona","Queijo minas com azeitona e tomate",["lanche","ceia"],
 [("queijo_minas",60),("azeitona",25),("tomate",70)],"Em pote, com azeite e orégano.",5),

# ---------------------------------------------- vitaminas em garrafa
("lv_vitamina_banana","Vitamina de banana e aveia na garrafa",["lanche","cafe"],
 [("leite",250),("banana",100),("aveia",30)],"Bata de manhã e leve na garrafa térmica.",5),
("lv_vitamina_mamao","Vitamina de mamão com linhaça",["lanche","cafe"],
 [("leite",230),("mamao",150),("linhaca",10)],"Boa para o intestino.",5),
("lv_vitamina_morango","Vitamina de morango com iogurte",["lanche","cafe"],
 [("iogurte",150),("morango",120),("mel",8)],"Leve gelada, com bastante gelo.",5),
("lv_vitamina_abacate","Vitamina de abacate com cacau",["lanche","ceia"],
 [("abacate",90),("leite",180),("cacau",8)],"Cremosa e sacia bem.",5),
("lv_vitamina_soja_manga","Vitamina de soja com manga",["lanche","cafe"],
 [("leite_soja",240),("manga",140),("aveia",25)],"Vegana.",5),
("lv_vitamina_coco_banana","Vitamina de leite de coco com banana",["lanche"],
 [("leite_coco",180),("banana",100),("aveia",25)],"Vegana e bem cremosa.",5),
("lv_suco_verde","Suco verde de couve com laranja",["lanche","cafe"],
 [("couve",50),("laranja",180),("linhaca",8)],"Bata na hora e leve na garrafa gelada.",6),
("lv_agua_coco_fruta","Água de coco com fruta picada",["lanche","ceia"],
 [("agua_coco",300),("melancia",150)],"Hidratação e fruta no mesmo lanche.",4),

# ---------------------------------------------- secos, sem geladeira
("lv_pipoca_pote","Pipoca em pote",["lanche"],
 [("pipoca",30)],"Estoure de manhã e leve em pote fechado. Aguenta o dia.",10),
("lv_pipoca_castanha","Pipoca com castanhas",["lanche"],
 [("pipoca",25),("castanha_caju",18)],"Mistura salgada que engana bem a fome.",10),
("lv_barra_aveia","Barrinha caseira de aveia com banana",["lanche","ceia"],
 [("aveia",50),("banana",90),("amendoim",15),("mel",10)],
 "Amasse tudo, asse 20 min e corte em barras. Dura 5 dias em pote.",35),
("lv_barra_castanha","Barrinha de aveia com castanhas e cacau",["lanche","ceia"],
 [("aveia",50),("castanha_caju",20),("cacau",8),("mel",12),("banana",70)],
 "Mesma base, trocando o recheio.",35),
("lv_granola_caseira","Granola caseira em pote",["lanche","cafe","ceia"],
 [("aveia",50),("castanha_caju",15),("coco",10),("mel",10)],
 "Asse a aveia com o mel até dourar. Rende semanas.",30),
("lv_paçoca_amendoim","Doce de amendoim caseiro",["ceia","lanche"],
 [("amendoim",35),("mel",8)],"Amendoim triturado com mel, prensado em forminha.",15),
("lv_torrada_mel","Torradas com mel e canela",["lanche","ceia"],
 [("torrada",35),("mel",12)],"Seco, leve e não precisa de geladeira.",3),
("lv_biscoito_maisena_fruta","Biscoito com banana",["lanche","ceia"],
 [("cream_cracker",30),("banana",90)],"Duas coisas que aguentam a mochila.",2),
("lv_flocos_pote","Flocos de milho com castanhas",["lanche","cafe"],
 [("flocos_milho",45),("castanha_caju",15)],"Leve o leite à parte, se tiver onde guardar.",3),
("lv_coco_banana_seca","Coco com banana",["lanche","ceia"],
 [("coco",25),("banana",100)],"Nada estraga, nada precisa esquentar.",2),
("lv_castanha_para_pote","Castanha-do-pará em porção",["lanche","ceia"],
 [("castanha_para",15)],"Duas ou três por dia já cobrem o selênio.",1),
("lv_amendoim_pote","Amendoim torrado em porção",["lanche","ceia"],
 [("amendoim",35)],"O lanche mais barato que existe.",1),

# ---------------------------------------------- marmitas frias (almoço/jantar)
("lv_salada_arroz_atum","Salada de arroz com atum e milho",["almoco","jantar","lanche"],
 [("arroz_branco",150),("atum_lata",80),("milho_verde",70),("tomate",60),("azeite",8)],
 "Marmita fria clássica: não precisa esquentar e não estraga fácil.",20),
("lv_salada_macarrao","Salada de macarrão com legumes e queijo",["almoco","jantar"],
 [("macarrao",80),("tomate",70),("queijo_minas",50),("azeitona",20),("azeite",10)],
 "Cozinhe a massa al dente e resfrie na hora para não grudar.",25),
("lv_salada_batata_ovo","Salada de batata com ovo e cheiro-verde",["almoco","jantar","lanche"],
 [("batata",170),("ovo_cozido",100),("cebola",30),("azeite",10),("salsa",8)],
 "Tempere ainda morna, leve gelada.",25),
("lv_tabule_pote","Tabule em pote",["almoco","jantar","lanche"],
 [("tabule",180),("grao_de_bico",80)],"Fica melhor no dia seguinte, quando pega o tempero.",25),
("lv_salada_fradinho","Salada de feijão-fradinho com atum",["almoco","jantar"],
 [("feijao_fradinho",140),("atum_lata",70),("tomate",60),("cebola",30),("azeite",8)],
 "Feijão-fradinho cozido firme aguenta bem a marmita.",35),
("lv_salada_grao_frango","Salada de grão-de-bico com frango",["almoco","jantar"],
 [("grao_de_bico",120),("frango_desfiado",100),("pepino",60),("tomate",60),("azeite",10)],
 "Proteína e leguminosa fria, sem depender de micro-ondas.",25),
("lv_salpicao_pote","Salpicão de frango em pote",["almoco","jantar","lanche"],
 [("salpicao",190)],"Fica melhor gelado — feito para levar.",30),
("lv_cuscuz_paulista_pote","Cuscuz paulista em fatia",["almoco","jantar","lanche"],
 [("cuscuz_paulista",190)],"Desenforme, fatie e leve. Bom frio.",35),
("lv_wrap_ovo_legumes","Wrap de omelete com legumes",["almoco","jantar","lanche"],
 [("pao_integral",60),("ovo_frito",100),("tomate",50),("alface",25)],
 "Omelete fino enrolado no pão; aguenta frio.",15),
]

# lanches que aguentam o dia inteiro fora da geladeira e não precisam de forno
# nem micro-ondas no trabalho
PORT_SECO = {
 "lv_mix_castanhas","lv_banana_castanha","lv_maca_amendoa","lv_pera_castanha",
 "lv_tangerina_amendoim","lv_uva_amendoa","lv_mexerica_castanha","lv_goiaba_castanha",
 "lv_caqui_amendoa","lv_ameixa_noz","lv_abacaxi_hortela","lv_pipoca_pote",
 "lv_pipoca_castanha","lv_barra_aveia","lv_barra_castanha","lv_granola_caseira",
 "lv_paçoca_amendoim","lv_torrada_mel","lv_biscoito_maisena_fruta","lv_flocos_pote",
 "lv_coco_banana_seca","lv_castanha_para_pote","lv_amendoim_pote","lv_crispy_grao",
 "lv_bolo_banana_aveia","lv_bolo_cenoura_cacau","lv_bolo_fuba","lv_bolo_integral_maca",
 "lv_biscoito_polvilho","lv_pao_caseiro_queijo","lv_bolinho_batata_doce",
 "lv_sand_presunto_queijo","lv_cracker_queijo","lv_banana_passa_aveia",
}
