# -*- coding: utf-8 -*-
# Ampliação do banco: ingredientes e preparações extras.
# Importado por build_dados.py. Todos os ingredientes vêm da TACO.
# As instruções de preparo são escritas aqui, não copiadas de sites.

# slug: (taco_id, nome curto, R$/kg (ou R$/L), rend, medida, [alergenos])
EXTRA_ING = {
 # ---------------- carboidratos
 "pao_aveia":        (48,  "Pão de forma com aveia",      24.00, 1.0, "fatia", ["gluten"]),
 "pao_soja":         (49,  "Pão de soja",                 24.00, 1.0, "fatia", ["gluten","soja"]),
 "pao_milho":        (51,  "Pão de milho",                22.00, 1.0, "fatia", ["gluten"]),
 "pao_sovado":       (54,  "Pão sovado",                  18.00, 1.0, "un",    ["gluten"]),
 "farinha_trigo":    (35,  "Farinha de trigo",             6.00, 1.0, "cru",   ["gluten"]),
 "macarrao_ovos":    (41,  "Macarrão com ovos",           11.00, 1.0, "cru",   ["gluten","ovo"]),
 "nhoque":           (136, "Nhoque de batata",            18.00, 1.0, "cozido",["gluten"]),
 "cuscuz_milho":     (533, "Cuscuz de milho",              7.00, 1.0, "cozido",[]),
 "cuscuz_paulista":  (534, "Cuscuz paulista",             14.00, 1.0, "pronto",["peixe"]),
 "canjica":          (19,  "Canjica branca",               9.00, .40, "cozida",[]),
 "flocos_milho":     (22,  "Flocos de milho",             22.00, 1.0, "cru",   []),
 "pipoca":           (61,  "Pipoca",                      12.00, 1.0, "pronta",[]),
 "inhame":           (126, "Inhame cozido",                8.00, 1.30,"cozido",[]),
 "cara":             (102, "Cará cozido",                  8.00, 1.30,"cozido",[]),
 "batata_baroa":     (86,  "Batata-baroa cozida",         12.00, 1.25,"cozida",[]),
 # ---------------- proteínas
 "frango_caipira":   (393, "Frango caipira cozido",       26.00, 1.30,"cozido",["frango"]),
 "frango_assado":    (403, "Frango assado sem pele",      18.00, 1.30,"assado",["frango"]),
 "coracao_frango":   (395, "Coração de frango grelhado",  30.00, 1.20,"grelh.",["frango"]),
 "frango_milanesa":  (401, "Filé de frango à milanesa",   28.00, 1.20,"frito", ["frango","gluten","ovo"]),
 "alcatra":          (370, "Miolo de alcatra grelhado",   55.00, 1.30,"grelh.",["boi"]),
 "maminha":          (368, "Maminha grelhada",            52.00, 1.30,"grelh.",["boi"]),
 "lagarto":          (363, "Lagarto cozido",              45.00, 1.30,"cozido",["boi"]),
 "coxao_duro":       (349, "Coxão duro cozido",           42.00, 1.30,"cozido",["boi"]),
 "cupim":            (353, "Cupim assado",                55.00, 1.35,"assado",["boi"]),
 "file_mignon":      (358, "Filé mignon grelhado",        75.00, 1.30,"grelh.",["boi"]),
 "carne_seca":       (384, "Carne seca cozida",           60.00, 1.40,"cozida",["boi"]),
 "hamburguer":       (417, "Hambúrguer caseiro grelhado", 35.00, 1.25,"grelh.",["boi"]),
 "pernil":           (435, "Pernil assado",               34.00, 1.30,"assado",["porco"]),
 "quibe":            (440, "Quibe assado",                30.00, 1.15,"assado",["boi","gluten"]),
 "abadejo":          (273, "Abadejo assado",              30.00, 1.25,"assado",["peixe"]),
 "cacao":            (282, "Posta de cação cozida",       35.00, 1.25,"cozida",["peixe"]),
 "corvina":          (293, "Corvina assada",              28.00, 1.25,"assada",["peixe"]),
 "bacalhau":         (280, "Bacalhau refogado",           90.00, 1.30,"refog.",["peixe"]),
 "sardinha_fresca":  (318, "Sardinha assada",             22.00, 1.20,"assada",["peixe"]),
 "ovo_codorna":      (485, "Ovo de codorna",              45.00, 1.0, "un",    ["ovo"]),
 "clara":            (486, "Clara de ovo cozida",         20.00, 1.0, "un",    ["ovo"]),
 # ---------------- laticínios
 "queijo_prato":     (467, "Queijo prato",                50.00, 1.0, "fatia", ["lactose"]),
 "minas_meia_cura":  (462, "Queijo minas meia cura",      55.00, 1.0, "fatia", ["lactose"]),
 "iogurte_desnatado":(449, "Iogurte natural desnatado",   15.00, 1.0, "pote",  ["lactose"]),
 "leite_fermentado": (460, "Leite fermentado",            20.00, 1.0, "ml",    ["lactose"]),
 "leite_po":         (459, "Leite em pó integral",        45.00, 1.0, "-",     ["lactose"]),
 "leite_coco":       (523, "Leite de coco",               25.00, 1.0, "ml",    []),
 "achocolatado":     (491, "Achocolatado em pó",          25.00, 1.0, "-",     ["lactose"]),
 # ---------------- leguminosas
 "feijao_fradinho":  (563, "Feijão fradinho cozido",      12.00, .42, "cozido",[]),
 "feijao_roxo":      (573, "Feijão roxo cozido",          12.00, .42, "cozido",[]),
 "ervilha_vagem":    (559, "Ervilha em vagem",            16.00, 1.0, "cru",   []),
 "tremoco":          (586, "Tremoço em conserva",         35.00, 1.0, "escor.",[]),
 "broto_feijao":     (125, "Broto de feijão",             14.00, 1.0, "cru",   []),
 # ---------------- hortaliças
 "agriao":           (75,  "Agrião",                      22.00, 1.0, "cru",   []),
 "acelga":           (74,  "Acelga",                      10.00, 1.0, "cru",   []),
 "almeirao":         (85,  "Almeirão refogado",           12.00, 1.15,"refog.",[]),
 "catalonha":        (106, "Catalonha refogada",          12.00, 1.15,"refog.",[]),
 "mostarda_folha":   (135, "Folha de mostarda",           14.00, 1.0, "cru",   []),
 "taioba":           (156, "Taioba",                      12.00, 1.15,"refog.",[]),
 "alho_poro":        (83,  "Alho-poró",                   18.00, 1.0, "cru",   []),
 "aipo":             (76,  "Salsão",                      14.00, 1.0, "cru",   []),
 "jilo":             (127, "Jiló",                        12.00, 1.15,"refog.",[]),
 "maxixe":           (134, "Maxixe",                      12.00, 1.15,"refog.",[]),
 "nabo":             (137, "Nabo",                         8.00, 1.15,"cozido",[]),
 "rabanete":         (148, "Rabanete",                    12.00, 1.0, "cru",   []),
 "pimentao_verm":    (145, "Pimentão vermelho",           14.00, 1.0, "cru",   []),
 "repolho_roxo":     (151, "Repolho roxo refogado",        8.00, 1.15,"refog.",[]),
 "espinafre_cru":    (119, "Espinafre cru",               20.00, 1.0, "cru",   []),
 "seleta":           (154, "Seleta de legumes",           14.00, 1.0, "escor.",[]),
 "azeitona":         (521, "Azeitona verde",              45.00, 1.0, "escor.",[]),
 "salsa":            (153, "Cheiro-verde",                30.00, 1.0, "cru",   []),
 "purê_tomate":      (160, "Purê de tomate",              14.00, 1.0, "-",     []),
 # ---------------- frutas
 "acai":             (168, "Polpa de açaí",               30.00, 1.0, "-",  []),
 "caju":             (186, "Caju",                        10.00, 1.0, "-",  []),
 "caqui":            (189, "Caqui",                       12.00, 1.0, "un", []),
 "figo":             (194, "Figo",                        30.00, 1.0, "un", []),
 "goiaba_branca":    (197, "Goiaba branca",                9.00, 1.0, "un", []),
 "graviola":         (201, "Graviola",                    15.00, 1.0, "-",  []),
 "jaca":             (204, "Jaca",                         8.00, 1.0, "-",  []),
 "kiwi":             (207, "Kiwi",                        25.00, 1.0, "un", []),
 "limao":            (220, "Limão",                        8.00, 1.0, "un", []),
 "mamao_formosa":    (225, "Mamão formosa",                6.00, 1.0, "-",  []),
 "maracuja":         (232, "Maracujá",                    10.00, 1.0, "un", []),
 "mexerica":         (237, "Mexerica",                     7.00, 1.0, "un", []),
 "pera":             (242, "Pera",                        15.00, 1.0, "un", []),
 "pessego":          (244, "Pêssego",                     18.00, 1.0, "un", []),
 "ameixa":           (172, "Ameixa",                      20.00, 1.0, "un", []),
 "banana_terra":     (175, "Banana da terra",              8.00, 1.0, "un", []),
 "banana_nanica":    (179, "Banana nanica",                6.00, 1.0, "un", []),
 "agua_coco":        (478, "Água de coco",                 8.00, 1.0, "ml", []),
 "mel":              (507, "Mel",                         40.00, 1.0, "-",  []),
 # ---------------- pratos prontos da TACO (base de receitas regionais)
 "baiao_dois":       (527, "Baião de dois",               16.00, 1.0, "pronto",["boi"]),
 "feijao_tropeiro":  (539, "Feijão tropeiro",             20.00, 1.0, "pronto",["porco","ovo"]),
 "feijoada":         (540, "Feijoada",                    26.00, 1.0, "pronto",["porco","boi"]),
 "arroz_carreteiro": (526, "Arroz carreteiro",            20.00, 1.0, "pronto",["boi"]),
 "virado_paulista":  (555, "Virado à paulista",           18.00, 1.0, "pronto",["porco","ovo"]),
 "estrog_frango":    (538, "Estrogonofe de frango",       28.00, 1.0, "pronto",["frango","lactose"]),
 "estrog_carne":     (537, "Estrogonofe de carne",        32.00, 1.0, "pronto",["boi","lactose"]),
 "salpicao":         (547, "Salpicão de frango",          24.00, 1.0, "pronto",["frango","ovo"]),
 "yakisoba":         (556, "Yakisoba",                    22.00, 1.0, "pronto",["gluten","soja"]),
 "bolonhesa":        (542, "Macarrão à bolonhesa",        18.00, 1.0, "pronto",["gluten","boi"]),
 "charuto_repolho":  (532, "Charuto de repolho",          20.00, 1.0, "pronto",["boi"]),
 "bolinho_arroz":    (530, "Bolinho de arroz",            18.00, 1.0, "pronto",["ovo","gluten"]),
 "tabule":           (549, "Tabule",                      16.00, 1.0, "pronto",["gluten"]),
 "quibebe":          (544, "Quibebe de abóbora",          10.00, 1.0, "pronto",[]),
 "salada_vapor":     (546, "Salada de legumes no vapor",  12.00, 1.0, "pronta",[]),
 "vatapa":           (554, "Vatapá",                      30.00, 1.0, "pronto",["peixe","frutos_mar","gluten"]),
 "vaca_atolada":     (553, "Vaca atolada",                22.00, 1.0, "pronto",["boi"]),
 "camarao_baiana":   (531, "Camarão à baiana",            60.00, 1.0, "pronto",["frutos_mar"]),
 "frango_acafrao":   (541, "Frango com açafrão",          24.00, 1.0, "pronto",["frango"]),
 "barreado":         (528, "Barreado",                    40.00, 1.0, "pronto",["boi"]),
 "manicoba":         (543, "Maniçoba",                    22.00, 1.0, "pronto",["porco"]),
 "acaraje":          (525, "Acarajé",                     20.00, 1.0, "un",    ["frutos_mar"]),
}

# (id, nome, [tipos], [(slug, gramas)], preparo, minutos)
EXTRA_P = [
# ================================================================ CAFÉ
("cafe_crepioca_queijo","Crepioca de queijo",["cafe","lanche"],
 [("tapioca",30),("ovo_frito",60),("queijo_minas",40),("laranja",130)],
 "Misture a goma com o ovo batido, despeje na frigideira antiaderente e recheie.",8),
("cafe_crepioca_frango","Crepioca recheada com frango",["cafe","lanche","jantar"],
 [("tapioca",30),("ovo_frito",60),("frango_desfiado",70),("tomate",40)],
 "Mesma massa da crepioca; o frango desfiado já temperado entra no recheio.",10),
("cafe_cuscuz_ovo_tomate","Cuscuz com ovo e tomate",["cafe"],
 [("cuscuz_milho",180),("ovo_frito",60),("tomate",60)],
 "Cuscuz na cuscuzeira; ovo na frigideira e tomate picado com azeite por cima.",15),
("cafe_cuscuz_paulista","Cuscuz paulista com café",["cafe","jantar"],
 [("cuscuz_paulista",180),("laranja",130)],
 "Fica melhor ainda morno, desenformado na hora.",25),
("cafe_panqueca_banana","Panqueca de banana com aveia",["cafe","lanche"],
 [("banana",100),("aveia",40),("ovo_frito",50),("mel",10)],
 "Amasse a banana, misture ovo e aveia e faça discos na frigideira quente.",12),
("cafe_pao_aveia_ovo","Pão de aveia com ovo e abacate",["cafe"],
 [("pao_aveia",50),("ovo_cozido",60),("abacate",60)],
 "Torre o pão, espalhe o abacate amassado com limão e fatie o ovo por cima.",10),
("cafe_vitamina_mamao","Vitamina de mamão com aveia",["cafe","lanche"],
 [("mamao",180),("leite",200),("aveia",30)],
 "Bata tudo gelado. O mamão dispensa açúcar.",5),
("cafe_acai_banana","Tigela de açaí com banana e aveia",["cafe","lanche"],
 [("acai",150),("banana",80),("aveia",30),("leite_soja",80)],
 "Bata o açaí com a bebida de soja até ficar cremoso; finalize com banana e aveia.",6),
("cafe_iogurte_mel","Iogurte desnatado com aveia e mel",["cafe","lanche","ceia"],
 [("iogurte_desnatado",170),("aveia",30),("mel",12),("morango",80)],
 "Monte no pote e leve pronto.",4),
("cafe_ovos_espinafre","Ovos mexidos com espinafre e torrada",["cafe","jantar"],
 [("ovo_frito",100),("espinafre",70),("torrada",30)],
 "Refogue o espinafre, escorra bem e junte aos ovos no fim.",12),
("cafe_tapioca_amendoim","Tapioca com banana e pasta de amendoim",["cafe","lanche"],
 [("tapioca",40),("banana",90),("amendoim",20)],
 "Recheie a tapioca com a banana em rodelas e o amendoim triturado.",8),
("cafe_tapioca_atum","Tapioca recheada com atum",["cafe","lanche","jantar"],
 [("tapioca",40),("atum_lata",70),("tomate",50)],
 "Atum escorrido temperado com limão e cebolinha.",8),
("cafe_pao_ovo_prato","Pão integral com ovo e queijo prato",["cafe"],
 [("pao_integral",50),("ovo_frito",55),("queijo_prato",30)],
 "Ovo frito sem gema mole se for levar na marmita.",8),
("cafe_mingau_cacau","Mingau de aveia com cacau",["cafe","ceia"],
 [("aveia",40),("leite",220),("cacau",8),("banana",70)],
 "Aveia e cacau no leite em fogo baixo, mexendo até engrossar.",8),
("cafe_canjica_leite","Canjica com leite e canela",["cafe","ceia"],
 [("canjica",180),("leite",120)],
 "Deixe o milho de molho na véspera; 40 min de panela de pressão.",50),
("cafe_pao_milho_requeijao","Pão de milho com queijo cremoso e mamão",["cafe"],
 [("pao_milho",60),("requeijao",30),("mamao",150)],
 "Pão levemente torrado.",6),
("cafe_batata_doce_ovo","Batata-doce com ovos e café",["cafe","lanche"],
 [("batata_doce",150),("ovo_cozido",100)],
 "Cozinhe a batata-doce na véspera; de manhã é só esquentar.",15),
("cafe_banana_linhaca","Banana amassada com aveia e linhaça",["cafe","lanche","ceia"],
 [("banana",110),("aveia",35),("linhaca",10)],
 "Vegano e pronto em dois minutos.",3),
("cafe_salada_frutas_coco","Salada de frutas com aveia e coco",["cafe","lanche","ceia"],
 [("mamao",120),("banana",70),("manga",90),("aveia",25),("coco",12)],
 "Corte tudo e regue com suco de limão para não escurecer.",8),
("cafe_smoothie_verde","Smoothie verde de couve com laranja",["cafe","lanche"],
 [("couve",50),("banana",90),("laranja",150),("linhaca",10)],
 "Bata a couve crua com o suco da laranja e a banana congelada.",5),
("cafe_pao_sovado_manteiga","Pão sovado com manteiga e café com leite",["cafe"],
 [("pao_sovado",60),("manteiga",10),("leite",180)],
 "O café da manhã mais brasileiro que existe.",5),
("cafe_cuscuz_queijo","Cuscuz com queijo e café",["cafe"],
 [("cuscuz_milho",180),("queijo_minas",50)],
 "Queijo por cima do cuscuz ainda quente, para derreter.",15),
("cafe_codorna_torrada","Ovos de codorna com torrada e tomate",["cafe","lanche"],
 [("ovo_codorna",80),("torrada",30),("tomate",60)],
 "Oito ovos de codorna cozinham em 4 minutos.",10),
("cafe_crepioca_doce","Crepioca doce com banana",["cafe","ceia"],
 [("tapioca",30),("ovo_frito",55),("banana",90),("mel",8)],
 "Mesma massa, recheio de banana amassada com canela.",8),
("cafe_aveia_overnight","Aveia da noite anterior com iogurte e morango",["cafe","lanche"],
 [("aveia",45),("iogurte",150),("morango",90)],
 "Misture na véspera e deixe na geladeira; de manhã está pronto.",5),
("cafe_flocos_milho","Flocos de milho com leite e banana",["cafe","lanche"],
 [("flocos_milho",45),("leite",200),("banana_nanica",80)],
 "Simples e rápido nos dias corridos.",3),
("cafe_pao_queijo_ovo","Pão de queijo com ovos mexidos",["cafe"],
 [("pao_queijo",70),("ovo_frito",90)],
 "Pão de queijo do congelador e ovos na frigideira ao mesmo tempo.",20),
("cafe_tapioca_couve","Tapioca com ovo e couve",["cafe","jantar"],
 [("tapioca",40),("ovo_frito",60),("couve",40)],
 "Couve bem fininha refogada rápido no alho.",10),
("cafe_wrap_omelete","Omelete enrolado com frango",["cafe","lanche","jantar"],
 [("ovo_frito",100),("frango_desfiado",70),("tomate",50)],
 "Faça um omelete fino, recheie e enrole como panqueca.",12),
("cafe_inhame_ovo","Inhame cozido com ovos",["cafe","lanche"],
 [("inhame",160),("ovo_cozido",100)],
 "Inhame cozido com casca solta fácil e sacia bastante.",20),

# ============================================================== LANCHE
("lanche_iogurte_desnatado","Iogurte desnatado com morango",["lanche","ceia"],
 [("iogurte_desnatado",170),("morango",100)],"Amasse parte da fruta para adoçar.",3),
("lanche_maca_amendoim","Maçã com pasta de amendoim",["lanche","ceia"],
 [("maca",130),("amendoim",20)],"Maçã em fatias com o amendoim triturado.",3),
("lanche_uva_castanha","Uva com castanha-do-pará",["lanche","ceia"],
 [("uva",120),("castanha_para",12)],"Duas castanhas por dia já bastam.",2),
("lanche_sanduiche_atum","Sanduíche de atum no pão integral",["lanche","jantar"],
 [("pao_integral",50),("atum_lata",80),("alface",20),("tomate",40)],
 "Atum com limão e cebolinha no lugar da maionese.",7),
("lanche_codorna_tomate","Ovos de codorna com tomate",["lanche"],
 [("ovo_codorna",90),("tomate",80)],"Deixe cozidos e descascados na geladeira.",10),
("lanche_pipoca_suco","Pipoca com suco de laranja",["lanche"],
 [("pipoca",30),("suco_laranja",250)],"Pipoca de panela com pouco óleo.",10),
("lanche_abacate_torrada","Abacate com limão na torrada",["lanche","ceia"],
 [("abacate",80),("torrada",30),("limao",10)],"Amasse com sal e limão.",4),
("lanche_banana_mel","Banana com aveia e mel",["lanche","ceia"],
 [("banana",100),("aveia",25),("mel",10)],"Rápido e barato.",3),
("lanche_tapioca_queijo","Tapioca com queijo minas",["lanche"],
 [("tapioca",40),("queijo_minas",50)],"Clássico da tarde.",7),
("lanche_palitos_ricota","Palitos de cenoura e pepino com pasta de ricota",["lanche"],
 [("cenoura_crua",70),("pepino",70),("ricota",60)],
 "Ricota amassada com azeite, sal e cheiro-verde.",7),
("lanche_homus","Homus de grão-de-bico com cenoura",["lanche","ceia"],
 [("grao_de_bico",80),("azeite",8),("limao",10),("cenoura_crua",70)],
 "Bata o grão cozido com azeite, limão e alho; sirva com palitos de cenoura.",12),
("lanche_acai_iogurte","Açaí com iogurte e banana",["lanche"],
 [("acai",120),("iogurte",120),("banana",70)],"Bata rápido para não derreter.",5),
("lanche_pera_castanha","Pera com castanha-do-pará",["lanche","ceia"],
 [("pera",150),("castanha_para",12)],"Fruta e gordura boa juntas seguram mais a fome.",2),
("lanche_kiwi_iogurte","Kiwi com iogurte natural",["lanche","ceia"],
 [("kiwi",140),("iogurte",150)],"Kiwi bem maduro dispensa mel.",3),
("lanche_sanduiche_peru_prato","Sanduíche de peru com queijo prato",["lanche"],
 [("pao_integral",50),("peru",40),("queijo_prato",25),("alface",20)],
 "Prense por três minutos na frigideira.",8),
("lanche_ovo_abacate","Ovo cozido com abacate",["lanche","ceia"],
 [("ovo_cozido",100),("abacate",70)],"Proteína e gordura boa, quase zero carboidrato.",10),
("lanche_melao_presunto","Melão com presunto magro",["lanche"],
 [("melao",180),("presunto",40)],"Combinação doce e salgada que funciona.",4),
("lanche_pasta_sardinha","Torrada com pasta de sardinha",["lanche","jantar"],
 [("torrada",30),("sardinha_lata",70),("limao",8)],
 "Amasse a sardinha com limão e cebolinha.",6),
("lanche_manga_linhaca","Manga com linhaça e iogurte",["lanche","ceia"],
 [("manga",150),("linhaca",10),("iogurte",120)],"Linhaça moída na hora rende mais.",4),
("lanche_tremoco","Tremoço com limão",["lanche","ceia"],
 [("tremoco",120),("limao",10)],"Vegano, proteico e barato.",2),
("lanche_vitamina_coco","Vitamina de leite de coco com banana",["lanche","cafe"],
 [("leite_coco",150),("banana",100),("aveia",25)],"Vegano e bem cremoso.",5),
("lanche_mamao_granola","Mamão com aveia e mel",["lanche","ceia","cafe"],
 [("mamao_formosa",200),("aveia",30),("mel",10)],"Bom para quem tem intestino preso.",4),
("lanche_caju_castanha","Caju com castanha de caju",["lanche"],
 [("caju",150),("castanha_caju",20)],"A fruta e a castanha vêm do mesmo pé.",3),
("lanche_figo_ricota","Figo com ricota",["lanche","ceia"],
 [("figo",120),("ricota",60)],"Doçura da fruta com a proteína da ricota.",3),
("lanche_batata_doce_canela","Batata-doce assada com canela",["lanche","ceia"],
 [("batata_doce",180)],"Asse em rodelas a 200 °C por 25 min e polvilhe canela.",30),
("lanche_milho_azeite","Milho verde com azeite",["lanche","ceia"],
 [("milho_verde",130),("azeite",6)],"Escorra bem e tempere com azeite e sal.",5),
("lanche_tapioca_abacate","Tapioca com abacate",["lanche","cafe"],
 [("tapioca",40),("abacate",80),("limao",8)],"Vegano e sacia bastante.",7),
("lanche_cracker_queijo","Cream cracker com queijo e suco de maracujá",["lanche"],
 [("cream_cracker",30),("queijo_minas",40),("maracuja",60)],"Suco batido sem açúcar.",5),
("lanche_salada_fruta_iogurte","Salada de frutas com iogurte",["lanche","ceia"],
 [("mamao",100),("banana",60),("maca",80),("iogurte",120)],"Corte tudo e misture na hora.",8),
("lanche_pipoca_castanha","Pipoca com castanhas",["lanche"],
 [("pipoca",25),("castanha_caju",20)],"Pipoca sem manteiga com um punhado de castanhas.",10),
("lanche_agua_coco_banana","Água de coco com banana",["lanche","ceia"],
 [("agua_coco",300),("banana",90)],"Repõe potássio depois do treino.",2),
("lanche_leite_fermentado","Leite fermentado com mamão",["lanche","ceia"],
 [("leite_fermentado",180),("mamao",150)],"Boa dupla para o intestino.",3),

# ============================================================== ALMOÇO
("almoco_baiao_frango","Baião de dois com frango e couve",["almoco","jantar"],
 [("baiao_dois",220),("frango_peito",110),("couve",60)],
 "Baião feito com feijão-de-corda; o frango vai grelhado por cima.",45),
("almoco_tropeiro_bife","Feijão tropeiro com bife e couve",["almoco"],
 [("feijao_tropeiro",180),("patinho",110),("couve",60)],
 "Tropeiro com a farinha entrando por último, fora do fogo.",40),
("almoco_feijoada_couve","Feijoada com arroz, couve e laranja",["almoco"],
 [("feijoada",200),("arroz_branco",120),("couve",60),("laranja",100)],
 "A laranja não é enfeite: ajuda a digerir a gordura.",60),
("almoco_carreteiro","Arroz carreteiro com salada",["almoco","jantar"],
 [("arroz_carreteiro",250),("alface",40),("tomate",60)],
 "Prato gaúcho de uma panela só, ótimo para aproveitar sobra de carne.",35),
("almoco_virado_paulista","Virado à paulista",["almoco"],
 [("virado_paulista",280),("couve",50)],
 "Feijão amassado com farinha, bisteca, ovo e couve.",40),
("almoco_estrogonofe_frango","Estrogonofe de frango com arroz",["almoco","jantar"],
 [("estrog_frango",200),("arroz_branco",150),("alface",40)],
 "Use creme de leite no fim, sem deixar ferver.",30),
("almoco_estrogonofe_carne","Estrogonofe de carne com arroz integral",["almoco","jantar"],
 [("estrog_carne",200),("arroz_integral",150),("brocolis",80)],
 "Carne em tiras selada em fogo alto antes do molho.",35),
("almoco_yakisoba","Yakisoba de frango e legumes",["almoco","jantar"],
 [("yakisoba",300),("frango_peito",90)],
 "Legumes em fogo alto e rápido, para ficarem crocantes.",30),
("almoco_bolonhesa","Macarrão à bolonhesa com salada",["almoco","jantar"],
 [("bolonhesa",280),("rucula",40),("tomate",50)],
 "Molho no fogo baixo por 30 min muda tudo.",40),
("almoco_charuto","Charuto de repolho com arroz",["almoco"],
 [("charuto_repolho",220),("arroz_branco",130)],
 "Escalde as folhas de repolho antes de enrolar.",60),
("almoco_quibebe_frango","Quibebe de abóbora com frango desfiado",["almoco","jantar"],
 [("quibebe",200),("frango_desfiado",110),("arroz_branco",120)],
 "Abóbora desmanchada no próprio caldo.",40),
("almoco_vaca_atolada","Vaca atolada com couve",["almoco"],
 [("vaca_atolada",300),("couve",60)],
 "Costela cozida até soltar do osso, com mandioca desmanchando.",70),
("almoco_barreado","Barreado com arroz e farinha",["almoco"],
 [("barreado",200),("arroz_branco",130),("farinha_mandioca",25),("banana",60)],
 "Prato do litoral do Paraná; tradicionalmente vai com banana.",90),
("almoco_frango_acafrao","Frango com açafrão, arroz e brócolis",["almoco","jantar"],
 [("frango_acafrao",220),("arroz_branco",140),("brocolis",90)],
 "Açafrão-da-terra dá a cor e o aroma.",35),
("almoco_salpicao","Salpicão de frango com arroz",["almoco","jantar"],
 [("salpicao",200),("arroz_branco",130)],
 "Fica melhor gelado, feito na véspera.",30),
("almoco_abadejo_baroa","Abadejo assado com batata-baroa e vagem",["almoco","jantar"],
 [("abadejo",150),("batata_baroa",160),("vagem",90),("azeite",8)],
 "Peixe branco a 200 °C por 18 min com limão e alho.",35),
("almoco_cacao_pirao","Cação com pirão, arroz e salada",["almoco"],
 [("cacao",150),("farinha_mandioca",25),("arroz_branco",140),("tomate",60)],
 "Use o caldo do peixe para o pirão, mexendo sem parar.",40),
("almoco_corvina_assada","Corvina assada com arroz e salada",["almoco","jantar"],
 [("corvina",160),("arroz_branco",140),("alface",40),("tomate",60),("azeite",8)],
 "Peixe inteiro no forno com rodelas de limão dentro.",40),
("almoco_bacalhau","Bacalhau com batata e brócolis",["almoco"],
 [("bacalhau",130),("batata",160),("brocolis",90),("azeite",10)],
 "Dessalgue trocando a água por 24 h na geladeira.",45),
("almoco_camarao_baiana","Camarão à baiana com arroz",["almoco"],
 [("camarao_baiana",220),("arroz_branco",140)],
 "Leite de coco e dendê no fim, fogo baixo.",35),
("almoco_vatapa","Vatapá com arroz",["almoco"],
 [("vatapa",200),("arroz_branco",140)],
 "Pão amolecido no leite de coco batido com amendoim e castanha.",50),
("almoco_manicoba","Maniçoba com arroz e farinha",["almoco"],
 [("manicoba",220),("arroz_branco",130),("farinha_mandioca",20)],
 "A folha de mandioca precisa de dias de cozimento — normalmente se compra pronta.",60),
("almoco_acaraje","Acarajé com salada",["almoco"],
 [("acaraje",120),("alface",50),("tomate",70)],
 "Massa de feijão-fradinho frita no dendê. Prato de exceção, não de todo dia.",45),
("almoco_frango_caipira","Frango caipira com quiabo e polenta",["almoco"],
 [("frango_caipira",150),("quiabo",100),("polenta",160)],
 "Frango caipira pede panela de pressão, uns 30 min.",60),
("almoco_alcatra","Alcatra grelhada com arroz, feijão e salada",["almoco"],
 [("alcatra",130),("arroz_branco",150),("feijao_carioca",130),("alface",40),("tomate",60)],
 "Chapa bem quente, 3 min de cada lado, sal só no fim.",30),
("almoco_maminha_mandioca","Maminha com mandioca e vinagrete",["almoco"],
 [("maminha",140),("mandioca",170),("tomate",60),("cebola",40),("azeite",8)],
 "Maminha na brasa ou na frigideira de ferro.",40),
("almoco_lagarto_pure","Lagarto cozido com purê e vagem",["almoco"],
 [("lagarto",130),("batata",160),("leite",40),("vagem",90)],
 "Lagarto fatiado fino depois de cozido, senão fica duro.",60),
("almoco_cupim_farofa","Cupim assado com arroz e farofa",["almoco"],
 [("cupim",130),("arroz_branco",140),("farofa",35),("repolho",60)],
 "Cupim quer forno baixo e tempo — 3 h a 160 °C.",180),
("almoco_file_mignon","Filé mignon com legumes salteados",["almoco","jantar"],
 [("file_mignon",130),("abobrinha",90),("cenoura",70),("arroz_integral",130),("azeite",8)],
 "Medalhão selado, 4 min de cada lado.",30),
("almoco_carne_seca_abobora","Carne seca com abóbora e arroz",["almoco"],
 [("carne_seca",110),("abobora",180),("arroz_branco",130)],
 "Dessalgue a carne seca na véspera e desfie.",50),
("almoco_pernil_batata_doce","Pernil assado com batata-doce",["almoco"],
 [("pernil",130),("batata_doce",170),("repolho_roxo",70)],
 "Pernil marinado de véspera com alho, laranja e alecrim.",120),
("almoco_quibe_tabule","Quibe assado com tabule",["almoco","jantar"],
 [("quibe",150),("tabule",150)],
 "Quibe de forno é bem menos gorduroso que o frito.",50),
("almoco_hamburguer_caseiro","Hambúrguer caseiro com arroz, feijão e salada",["almoco","jantar"],
 [("hamburguer",130),("arroz_branco",140),("feijao_carioca",120),("alface",40)],
 "Só carne moída, sal e pimenta; a frigideira tem que estar muito quente.",25),
("almoco_frango_milanesa","Frango à milanesa com arroz e salada",["almoco"],
 [("frango_milanesa",140),("arroz_branco",140),("alface",40),("tomate",60)],
 "No forno com um fio de azeite fica quase igual ao frito.",35),
("almoco_nhoque_frango","Nhoque ao sugo com frango desfiado",["almoco","jantar"],
 [("nhoque",200),("molho_tomate",100),("frango_desfiado",90),("parmesao",10)],
 "O nhoque está pronto quando sobe à superfície.",35),
("almoco_coracao_frango","Coração de frango com arroz e salada",["almoco"],
 [("coracao_frango",130),("arroz_branco",140),("feijao_carioca",120),("agriao",40)],
 "Limpe bem e grelhe em fogo alto com alho.",35),
("almoco_coxao_duro_legumes","Coxão duro cozido com legumes",["almoco"],
 [("coxao_duro",130),("cenoura",80),("batata",130),("arroz_branco",120)],
 "Panela de pressão por 30 min, legumes nos últimos 10.",50),
("almoco_feijao_fradinho","Arroz com feijão-fradinho e ovo",["almoco","jantar"],
 [("feijao_fradinho",150),("arroz_branco",140),("ovo_cozido",50),("couve",50)],
 "Fradinho cozinha mais rápido que o carioca.",35),
("almoco_sardinha_fresca","Sardinha assada com arroz e salada",["almoco","jantar"],
 [("sardinha_fresca",150),("arroz_branco",140),("tomate",70),("cebola",40)],
 "Peixe barato, rico em ômega-3. Forno alto por 15 min.",30),

# ============================================================== JANTAR
("jantar_sopa_abobora_carne","Sopa de abóbora com carne desfiada",["jantar"],
 [("abobora",230),("musculo",100),("cebola",40),("couve",40)],
 "Cozinhe a carne primeiro e use o caldo dela na abóbora.",50),
("jantar_sopa_baroa","Sopa de mandioquinha com frango",["jantar"],
 [("batata_baroa",200),("frango_desfiado",100),("cenoura",60),("salsa",8)],
 "A mandioquinha engrossa sozinha, sem precisar de creme.",40),
("jantar_caldo_verde","Caldo verde com couve e batata",["jantar"],
 [("batata",200),("couve",50),("linguica_frango",60),("azeite",8)],
 "Bata a batata cozida e junte a couve fatiada bem fina no fim.",35),
("jantar_canja","Canja de galinha",["jantar"],
 [("arroz_branco",100),("frango_desfiado",110),("cenoura",70),("salsa",8)],
 "Arroz cozinhando no caldo do frango é o segredo.",40),
("jantar_sopa_inhame","Sopa de inhame com frango",["jantar"],
 [("inhame",200),("frango_desfiado",100),("cebola",40)],
 "Inhame batido deixa o caldo aveludado.",40),
("jantar_creme_couveflor","Creme de couve-flor com frango",["jantar"],
 [("couve_flor",220),("frango_desfiado",100),("leite",60)],
 "Couve-flor cozida e batida vira creme sem farinha nenhuma.",35),
("jantar_sopa_fradinho","Sopa de feijão-fradinho com legumes",["jantar"],
 [("feijao_fradinho",160),("cenoura",70),("abobora",90),("couve",40)],
 "Bata metade do feijão para engrossar.",40),
("jantar_escondidinho_carne","Escondidinho de carne com purê de mandioca",["jantar","almoco"],
 [("mandioca",200),("acem_moido",110),("leite",30),("mussarela",25)],
 "Mandioca cozida e amassada ainda quente, carne temperada por baixo.",50),
("jantar_escondidinho_frango","Escondidinho de frango com batata-doce",["jantar","almoco"],
 [("batata_doce",200),("frango_desfiado",110),("requeijao",25)],
 "Batata-doce dá um purê naturalmente doce que combina com o frango.",45),
("jantar_omelete_prato","Omelete de queijo prato com salada",["jantar"],
 [("ovo_frito",110),("queijo_prato",30),("alface",40),("tomate",60)],
 "Três ovos, queijo no meio e dobra.",15),
("jantar_wrap_atum","Wrap de atum com salada",["jantar","lanche"],
 [("pao_integral",60),("atum_lata",80),("alface",40),("cenoura_crua",50)],
 "Monte na hora para o pão não umedecer.",10),
("jantar_salada_grao_ovo","Salada de grão-de-bico com ovo",["jantar"],
 [("grao_de_bico",120),("ovo_cozido",100),("tomate",70),("pepino",60),("azeite",10)],
 "Deixe o grão cozido na geladeira para a semana.",15),
("jantar_salada_lentilha","Salada de lentilha com legumes",["jantar"],
 [("lentilha",150),("cenoura_crua",60),("pimentao_verm",50),("azeite",10),("limao",10)],
 "Vegana, servida fria ou morna.",30),
("jantar_abobrinha_recheada","Abobrinha recheada com carne moída",["jantar","almoco"],
 [("abobrinha",200),("acem_moido",110),("molho_tomate",70),("mussarela",25)],
 "Cave a abobrinha ao meio, recheie e asse por 25 min.",40),
("jantar_berinjela_forno","Berinjela ao forno com queijo e tomate",["jantar"],
 [("berinjela",200),("molho_tomate",90),("mussarela",40),("azeite",8)],
 "Camadas de berinjela, molho e queijo — tipo uma lasanha sem massa.",45),
("jantar_pimentao_recheado","Pimentão recheado com frango e arroz",["jantar","almoco"],
 [("pimentao_verm",160),("frango_desfiado",100),("arroz_branco",90),("molho_tomate",60)],
 "Corte a tampa, recheie e asse coberto por 30 min.",45),
("jantar_chuchu_ovos","Chuchu refogado com ovos e arroz",["jantar"],
 [("chuchu",180),("ovo_frito",90),("arroz_branco",110)],
 "Chuchu refogado no alho, ovos por cima.",25),
("jantar_corvina_abobrinha","Corvina ao forno com abobrinha",["jantar"],
 [("corvina",150),("abobrinha",120),("batata",120),("azeite",8)],
 "Tudo na mesma assadeira, 25 min a 200 °C.",35),
("jantar_sardinha_batata_doce","Sardinha com salada de batata-doce",["jantar"],
 [("sardinha_lata",90),("batata_doce",150),("cebola",40),("salsa",8)],
 "Batata-doce morna absorve melhor o tempero.",25),
("jantar_tofu_curry","Tofu ao curry com legumes",["jantar"],
 [("tofu",150),("leite_coco",80),("cenoura",70),("abobrinha",80),("arroz_integral",120)],
 "Curry em pó no óleo antes de tudo, para soltar o aroma.",30),
("jantar_yakisoba_veg","Yakisoba vegetariano",["jantar"],
 [("yakisoba",280),("tofu",80)],"Sem carne, com tofu firme dourado.",25),
("jantar_macarrao_brocolis","Macarrão com brócolis e alho",["jantar"],
 [("macarrao",80),("brocolis",120),("alho",8),("azeite",12)],
 "Cozinhe o brócolis na mesma água da massa nos últimos 3 min.",20),
("jantar_polenta_ragu","Polenta com ragu de carne moída",["jantar","almoco"],
 [("polenta",180),("acem_moido",110),("molho_tomate",80)],
 "Polenta mole, ragu de fogo baixo.",40),
("jantar_cuscuz_paulista","Cuscuz paulista com salada",["jantar"],
 [("cuscuz_paulista",200),("alface",40),("tomate",60)],
 "Fica ótimo frio no dia seguinte.",35),
("jantar_sopa_lentilha_abobora","Sopa de lentilha com abóbora",["jantar"],
 [("lentilha",150),("abobora",150),("cebola",40),("azeite",8)],
 "Vegana e bem encorpada.",35),
("jantar_panqueca_espinafre","Panqueca de espinafre com ricota",["jantar"],
 [("farinha_trigo",40),("leite",80),("ovo_frito",50),("espinafre",80),("ricota",60)],
 "Massa fina batida no liquidificador.",35),
("jantar_salada_morna_batata","Salada morna de batata com ovo e vagem",["jantar"],
 [("batata",170),("ovo_cozido",100),("vagem",90),("azeite",10)],
 "Tempere ainda morna para pegar gosto.",25),
("jantar_frango_curry","Frango ao curry com arroz integral",["jantar","almoco"],
 [("frango_peito",130),("leite_coco",70),("arroz_integral",140),("cenoura",70)],
 "Leite de coco entra no fim, sem ferver.",30),
("jantar_bolinho_arroz","Bolinho de arroz assado com salada",["jantar"],
 [("bolinho_arroz",150),("alface",50),("tomate",60)],
 "Ótimo destino para o arroz que sobrou.",30),
("jantar_salada_tremoco","Salada de tremoço com legumes",["jantar"],
 [("tremoco",140),("tomate",70),("pepino",60),("cebola",30),("azeite",10)],
 "Vegana, proteica e sem fogão.",10),
("jantar_sopa_legumes_veg","Sopa de legumes com grão-de-bico",["jantar"],
 [("grao_de_bico",110),("cenoura",70),("batata",110),("abobrinha",80),("couve",40)],
 "Vegana. Amasse parte dos legumes para encorpar.",40),
("jantar_jilo_carne","Jiló refogado com carne moída e arroz",["jantar","almoco"],
 [("jilo",140),("acem_moido",100),("arroz_branco",120)],
 "Deixe o jiló de molho em água com sal para tirar o amargor.",30),
("jantar_salada_vapor_ovo","Legumes no vapor com ovos",["jantar"],
 [("salada_vapor",200),("ovo_cozido",100),("azeite",8)],
 "Jantar leve de dez minutos.",15),

# ================================================================ CEIA
("ceia_iogurte_canela","Iogurte desnatado com canela",["ceia"],
 [("iogurte_desnatado",170)],"Canela por cima, sem açúcar.",2),
("ceia_leite_cacau","Leite morno com cacau",["ceia"],
 [("leite",200),("cacau",6)],"Aquecer sem ferver.",4),
("ceia_banana_canela","Banana com canela",["ceia"],
 [("banana",100)],"Banana amassada com canela ajuda a dormir.",2),
("ceia_mamao_linhaca","Mamão com linhaça",["ceia"],
 [("mamao",180),("linhaca",10)],"Boa para o intestino funcionar de manhã.",3),
("ceia_kiwi","Kiwi",["ceia"],[("kiwi",140)],"Duas unidades, simples assim.",2),
("ceia_ovo","Ovo cozido",["ceia"],[("ovo_cozido",50)],"Proteína pura antes de dormir.",10),
("ceia_romeu_julieta","Queijo minas com goiabada de fruta",["ceia"],
 [("queijo_minas",50),("goiaba",120)],"Versão leve do Romeu e Julieta, com a fruta no lugar da goiabada.",3),
("ceia_agua_coco","Água de coco",["ceia"],[("agua_coco",300)],"Hidrata e é leve.",1),
("ceia_uva","Uva",["ceia"],[("uva",130)],"Um cacho pequeno.",1),
("ceia_iogurte_mel","Iogurte com mel",["ceia"],
 [("iogurte",170),("mel",10)],"Mel de verdade, uma colher de chá.",2),
("ceia_amendoa","Amêndoas",["ceia"],[("amendoa",20)],"Um punhado fechado na mão.",1),
("ceia_cracker_queijo","Cream cracker com queijo",["ceia"],
 [("cream_cracker",25),("queijo_minas",40)],"Leve o suficiente para não pesar.",3),
("ceia_leite_coco_cacau","Leite de coco com cacau",["ceia"],
 [("leite_coco",180),("cacau",6)],"Vegano e cremoso.",3),
("ceia_maca_assada","Maçã assada com canela",["ceia"],
 [("maca",150)],"Micro-ondas por 4 min com canela resolve.",6),
("ceia_melancia","Melancia",["ceia"],[("melancia",250)],"Refrescante e quase só água.",2),
("ceia_pera_noz","Pera com nozes",["ceia"],
 [("pera",150),("amendoa",15)],"Fruta com oleaginosa segura melhor a fome.",2),
("ceia_caqui","Caqui",["ceia"],[("caqui",150)],"Bem maduro, com colher.",2),
("ceia_mexerica","Mexerica",["ceia"],[("mexerica",150)],"Fácil de descascar, boa para a noite.",2),
]

# ================================================ ALMOÇOS SEM CARNE
EXTRA_P += [
("almoco_arroz_feijao_ovo","Arroz, feijão, ovo frito e salada",["almoco","jantar"],
 [("arroz_branco",150),("feijao_carioca",140),("ovo_frito",60),("alface",40),("tomate",60),("azeite",6)],
 "O prato brasileiro de todo dia. Ovo com a gema mole por cima do arroz.",25),
("almoco_escondidinho_lentilha","Escondidinho de lentilha com purê de mandioca",["almoco","jantar"],
 [("mandioca",200),("lentilha",150),("cebola",40),("azeite",10)],
 "Lentilha bem temperada com alho e cominho embaixo, mandioca amassada por cima.",45),
("almoco_estrogonofe_grao","Estrogonofe de grão-de-bico com arroz",["almoco","jantar"],
 [("grao_de_bico",140),("creme_leite",40),("molho_tomate",70),("arroz_branco",140)],
 "Mesmo molho do estrogonofe tradicional, com grão no lugar da carne.",30),
("almoco_moqueca_banana","Moqueca de banana da terra com arroz",["almoco","jantar"],
 [("banana_terra",180),("leite_coco",90),("pimentao_verm",60),("tomate",80),("arroz_branco",140)],
 "Vegana. Banana da terra em rodelas grossas, cozida no leite de coco com dendê ou azeite.",35),
("almoco_curry_grao","Curry de grão-de-bico com arroz integral",["almoco","jantar"],
 [("grao_de_bico",150),("leite_coco",80),("cenoura",70),("arroz_integral",140)],
 "Vegana. Curry em pó no óleo primeiro, depois o grão e o leite de coco.",30),
("almoco_risoto_abobora","Risoto de abóbora com parmesão",["almoco","jantar"],
 [("arroz_branco",160),("abobora",160),("parmesao",15),("cebola",40),("azeite",10)],
 "Abóbora desmancha e dá a cremosidade, sem precisar de creme de leite.",40),
("almoco_macarrao_ricota","Macarrão ao sugo com ricota e rúcula",["almoco","jantar"],
 [("macarrao",90),("molho_tomate",110),("ricota",70),("rucula",40)],
 "Rúcula entra crua no prato, murcha no calor da massa.",25),
("almoco_arroz_feijao_preto","Arroz integral com feijão preto, couve e ovo",["almoco","jantar"],
 [("arroz_integral",150),("feijao_preto",140),("couve",60),("ovo_cozido",50)],
 "Couve fatiada fina refogada rápido no alho.",30),
("almoco_tofu_parmegiana","Tofu à parmegiana com arroz",["almoco","jantar"],
 [("tofu",150),("molho_tomate",100),("mussarela",35),("arroz_integral",130)],
 "Tofu firme prensado, empanado ou só grelhado, coberto com molho e queijo.",35),
("almoco_torta_legumes","Torta de legumes de liquidificador com salada",["almoco","jantar"],
 [("farinha_trigo",60),("ovo_frito",55),("leite",90),("cenoura",70),("vagem",70),("alface",40)],
 "Bata os líquidos, misture os legumes picados e asse por 35 min.",50),
("almoco_feijoada_vegetariana","Feijoada vegetariana de feijão preto",["almoco"],
 [("feijao_preto",180),("abobora",100),("cenoura",70),("arroz_branco",130),("couve",60),("laranja",100)],
 "Vegana. Feijão preto com legumes firmes no lugar das carnes, defumado com páprica.",50),
("almoco_arroz_lentilha_abobora","Arroz com lentilha, abóbora e couve",["almoco","jantar"],
 [("arroz_integral",150),("lentilha",140),("abobora",120),("couve",50),("azeite",8)],
 "Vegana e bem completa em aminoácidos: arroz com leguminosa fecha a proteína.",35),
("almoco_berinjela_parmegiana","Berinjela à parmegiana com arroz",["almoco","jantar"],
 [("berinjela",200),("molho_tomate",100),("mussarela",40),("arroz_branco",130)],
 "Berinjela assada em vez de frita deixa o prato bem mais leve.",45),
("almoco_salada_completa","Salada completa de grão-de-bico, batata e ovo",["almoco","jantar"],
 [("grao_de_bico",130),("batata",140),("ovo_cozido",100),("tomate",70),("azeite",10),("limao",10)],
 "Almoço frio, bom para levar. Tempere ainda morno.",25),
("almoco_ovos_pimentao","Ovos com pimentão e cebola, arroz e feijão",["almoco","jantar"],
 [("ovo_frito",110),("pimentao_verm",70),("cebola",40),("arroz_branco",140),("feijao_carioca",120)],
 "Refogue os pimentões, jogue os ovos por cima e mexa pouco.",25),
("almoco_nhoque_sugo_veg","Nhoque ao sugo com queijo",["almoco","jantar"],
 [("nhoque",200),("molho_tomate",110),("parmesao",15),("rucula",30)],
 "Vegetariano. O nhoque sobe à superfície quando está pronto.",30),
]
