# -*- coding: utf-8 -*-
# Produtos industrializados que se compra pronto no mercado (linha "fitness").
# ATENÇÃO: estes NÃO estão na TACO. Os valores são médias de rótulo de produtos
# vendidos no Brasil e ficam marcados com rotulo=1 para o app avisar o usuário.
# Ids sintéticos a partir de 900 para não colidir com a TACO (1..597).

MERCADO_TACO = [
 dict(i=900, n="Iogurte proteico (copo)",          c="Leite e derivados", k=65,  p=10.0, b=6.0,  g=0.2, f=0.0, s=60,  sa=0.1, co=5,  fe=0.1),
 dict(i=901, n="Bebida láctea proteica (garrafa)", c="Leite e derivados", k=60,  p=10.0, b=4.0,  g=0.5, f=0.0, s=55,  sa=0.3, co=6,  fe=0.1),
 dict(i=902, n="Iogurte grego zero açúcar",        c="Leite e derivados", k=60,  p=9.0,  b=5.0,  g=0.3, f=0.0, s=50,  sa=0.2, co=4,  fe=0.1),
 dict(i=903, n="Whey protein em pó",               c="Miscelâneas",       k=380, p=78.0, b=8.0,  g=4.0, f=1.0, s=250, sa=1.5, co=15, fe=1.0),
 dict(i=904, n="Barra de proteína",                c="Miscelâneas",       k=350, p=30.0, b=40.0, g=9.0, f=6.0, s=280, sa=4.0, co=8,  fe=2.0),
 dict(i=905, n="Barra de cereal",                  c="Cereais e derivados",k=400,p=5.0,  b=70.0, g=11.0,f=4.0, s=180, sa=4.5, co=0,  fe=1.5),
 dict(i=906, n="Biscoito de arroz integral",       c="Cereais e derivados",k=387,p=8.0,  b=81.0, g=3.0, f=3.0, s=200, sa=0.6, co=0,  fe=1.0),
 dict(i=907, n="Granola de pacote",                c="Cereais e derivados",k=420,p=9.0,  b=65.0, g=14.0,f=7.0, s=30,  sa=3.0, co=0,  fe=2.5),
 dict(i=908, n="Pasta de amendoim integral",       c="Leguminosas e derivados",k=600,p=25.0,b=20.0,g=50.0,f=6.0,s=10, sa=8.0, co=0,  fe=2.0),
 dict(i=909, n="Chips de grão-de-bico",            c="Leguminosas e derivados",k=450,p=15.0,b=55.0,g=18.0,f=8.0,s=450,sa=2.0, co=0,  fe=3.0),
 dict(i=910, n="Banana-passa",                     c="Frutas e derivados",k=300, p=3.0,  b=78.0, g=0.8, f=6.0, s=5,   sa=0.3, co=0,  fe=1.0),
 dict(i=911, n="Damasco seco",                     c="Frutas e derivados",k=240, p=3.4,  b=63.0, g=0.5, f=7.0, s=10,  sa=0.0, co=0,  fe=2.7),
 dict(i=912, n="Uva-passa",                        c="Frutas e derivados",k=299, p=3.1,  b=79.0, g=0.5, f=3.7, s=11,  sa=0.1, co=0,  fe=1.9),
 dict(i=913, n="Mix de castanhas de pacote",       c="Nozes e sementes",  k=600, p=17.0, b=20.0, g=50.0,f=8.0, s=120, sa=7.0, co=0,  fe=3.0),
 dict(i=914, n="Atum em sachê",                    c="Pescados e frutos do mar",k=110,p=24.0,b=0.5,g=1.5,f=0.0,s=350, sa=0.5, co=45, fe=1.2),
 dict(i=915, n="Frango desfiado em conserva",      c="Carnes e derivados",k=120, p=22.0, b=1.0,  g=3.0, f=0.0, s=400, sa=1.0, co=55, fe=0.8),
 dict(i=916, n="Achocolatado pronto (caixinha)",   c="Leite e derivados", k=78,  p=3.0,  b=13.0, g=1.8, f=0.0, s=60,  sa=1.1, co=6,  fe=0.5),
 dict(i=917, n="Suco de fruta integral (caixinha)",c="Bebidas (alcoólicas e não alcoólicas)",k=45,p=0.5,b=11.0,g=0.1,f=0.2,s=5,sa=0.0,co=0,fe=0.2),
 dict(i=918, n="Queijo em porção individual",      c="Leite e derivados", k=300, p=22.0, b=2.0,  g=23.0,f=0.0, s=600, sa=14.0,co=70, fe=0.2),
 dict(i=919, n="Ovo cozido pronto (embalado)",     c="Ovos e derivados",  k=146, p=13.0, b=0.6,  g=9.5, f=0.0, s=140, sa=3.0, co=370,fe=1.8),
]
for x in MERCADO_TACO:
    x["rotulo"] = 1
    x.setdefault("ca", 0); x.setdefault("vc", 0)

# slug: (id, nome curto, R$/kg (ou R$/L), rend, medida, [alergenos])
MERCADO_ING = {
 "iog_proteico":   (900, "Iogurte proteico",           36.00, 1.0, "copo",  ["lactose"]),
 "bebida_prot":    (901, "Bebida láctea proteica",     40.00, 1.0, "garraf.",["lactose"]),
 "iog_grego":      (902, "Iogurte grego zero",         30.00, 1.0, "copo",  ["lactose"]),
 "whey":           (903, "Whey protein",              150.00, 1.0, "scoop", ["lactose"]),
 "barra_prot":     (904, "Barra de proteína",         200.00, 1.0, "un",    ["lactose","soja"]),
 "barra_cereal":   (905, "Barra de cereal",            60.00, 1.0, "un",    ["gluten"]),
 "biscoito_arroz": (906, "Biscoito de arroz",          40.00, 1.0, "un",    []),
 "granola_pct":    (907, "Granola de pacote",          30.00, 1.0, "-",     ["gluten","oleaginosas"]),
 "pasta_amendoim": (908, "Pasta de amendoim",          45.00, 1.0, "-",     ["amendoim"]),
 "chips_grao":     (909, "Chips de grão-de-bico",      80.00, 1.0, "pacote",[]),
 "banana_passa":   (910, "Banana-passa",               40.00, 1.0, "-",     []),
 "damasco":        (911, "Damasco seco",               90.00, 1.0, "-",     []),
 "uva_passa":      (912, "Uva-passa",                  35.00, 1.0, "-",     []),
 "mix_pct":        (913, "Mix de castanhas",           80.00, 1.0, "pacote",["oleaginosas"]),
 "atum_sache":     (914, "Atum em sachê",              90.00, 1.0, "sachê", ["peixe"]),
 "frango_conserva":(915, "Frango desfiado em conserva",70.00, 1.0, "lata",  ["frango"]),
 "achoc_pronto":   (916, "Achocolatado pronto",        12.00, 1.0, "cx",    ["lactose"]),
 "suco_cx":        (917, "Suco integral de caixinha",  14.00, 1.0, "cx",    []),
 "queijo_porcao":  (918, "Queijo em porção",           75.00, 1.0, "un",    ["lactose"]),
 "ovo_pronto":     (919, "Ovo cozido embalado",        60.00, 1.0, "un",    ["ovo"]),
}

# (id, nome, [tipos], [(slug, g)], preparo, minutos)
MERCADO_P = [
# ------------------------------------------- combos de pacote (zero preparo)
("mk_iog_castanha","Iogurte proteico com castanhas",["lanche","ceia","cafe"],
 [("iog_proteico",250),("mix_pct",30)],
 "Compra os dois prontos: o copo de iogurte proteico e um pacotinho de castanhas.",1),
("mk_iog_banana","Iogurte proteico com banana",["lanche","cafe","ceia"],
 [("iog_proteico",250),("banana",100)],"Só abrir o copo e levar a fruta.",1),
("mk_iog_granola","Iogurte proteico com granola",["lanche","cafe"],
 [("iog_proteico",250),("granola_pct",35)],"Granola em saquinho à parte, para não amolecer.",2),
("mk_bebida_barra","Bebida láctea proteica com barra de proteína",["lanche","ceia"],
 [("bebida_prot",250),("barra_prot",40)],"O combo de mochila: uma garrafinha e uma barra.",1),
("mk_bebida_fruta","Bebida láctea proteica com maçã",["lanche","ceia"],
 [("bebida_prot",250),("maca",130)],"Proteína pronta e uma fruta que não amassa.",1),
("mk_grego_frutas","Iogurte grego zero com morango",["lanche","ceia"],
 [("iog_grego",200),("morango",100)],"Versão mais barata que o proteico e com boa proteína.",2),
("mk_barra_fruta","Barra de proteína com banana",["lanche","ceia"],
 [("barra_prot",40),("banana",100)],"Cabe no bolso, resolve a tarde.",1),
("mk_mix_frutas_secas","Mix de castanhas com frutas secas",["lanche","ceia"],
 [("mix_pct",30),("uva_passa",25),("damasco",25)],
 "Monte um pote no domingo. Não estraga, não precisa de geladeira.",5),
("mk_chips_grao","Chips de grão-de-bico com suco de caixinha",["lanche"],
 [("chips_grao",40),("suco_cx",200)],"Salgadinho com proteína, comprado pronto.",1),
("mk_biscoito_pasta","Biscoito de arroz com pasta de amendoim",["lanche","ceia"],
 [("biscoito_arroz",30),("pasta_amendoim",20)],
 "Leve a pasta em potinho e passe na hora, para o biscoito não murchar.",3),
("mk_biscoito_queijo","Biscoito de arroz com queijo em porção",["lanche"],
 [("biscoito_arroz",30),("queijo_porcao",30)],"Aquelas porções individuais de queijo aguentam bem o dia.",1),
("mk_banana_passa_castanha","Banana-passa com castanhas",["lanche","ceia"],
 [("banana_passa",50),("mix_pct",25)],"Doce natural com gordura boa. Dura semanas.",1),
("mk_whey_banana","Shake de whey com banana",["lanche","cafe"],
 [("whey",30),("banana",100),("leite",250)],
 "Bata de manhã e leve na garrafa, ou leve o pó e misture com água no trabalho.",4),
("mk_whey_agua","Whey batido com água e fruta",["lanche","ceia"],
 [("whey",30),("agua_coco",250),("maca",120)],"Para quem não quer carregar leite.",3),
("mk_ovo_pronto_fruta","Ovos cozidos embalados com fruta",["lanche","cafe"],
 [("ovo_pronto",100),("tangerina",140)],
 "Os ovos cozidos em embalagem individual, que já vêm prontos no mercado.",1),
("mk_atum_biscoito","Atum em sachê com biscoito de arroz",["lanche","jantar"],
 [("atum_sache",80),("biscoito_arroz",30),("tomate",60)],
 "Sachê não precisa escorrer nem abridor. Um dos lanches proteicos mais baratos.",3),
("mk_frango_conserva_pao","Frango em conserva no pão integral",["lanche","jantar"],
 [("frango_conserva",80),("pao_integral",50),("alface",20)],"Abre a lata e monta na hora.",4),
("mk_achoc_barra","Achocolatado de caixinha com barra de cereal",["lanche"],
 [("achoc_pronto",200),("barra_cereal",25)],"O lanche de mochila mais fácil que existe.",1),
("mk_queijo_fruta","Queijo em porção com uva",["lanche","ceia"],
 [("queijo_porcao",30),("uva",120)],"Nada para preparar, nada para esquentar.",1),
("mk_pasta_amendoim_banana","Banana com pasta de amendoim",["lanche","ceia","cafe"],
 [("banana",110),("pasta_amendoim",20)],"Leve a pasta em potinho e a banana inteira.",2),

# ------------------------------------------- sanduíches para levar
("mk_sand_frango_conserva","Sanduíche de frango em conserva com cenoura",["lanche","jantar"],
 [("pao_integral",50),("frango_conserva",80),("cenoura_crua",40),("alface",20)],
 "Monte de manhã, embrulhe no papel-filme e leve.",6),
("mk_sand_atum_sache","Sanduíche de atum em sachê",["lanche","jantar"],
 [("pao_integral",50),("atum_sache",80),("tomate",40),("alface",20)],
 "O sachê é seco, então o pão não umedece como com a lata.",5),
("mk_sand_queijo_peru","Sanduíche de queijo em porção com peito de peru",["lanche"],
 [("pao_integral",50),("queijo_porcao",30),("peru",40),("tomate",35)],"Tudo comprado pronto.",4),
("mk_sand_pasta_amendoim","Sanduíche de pasta de amendoim com banana",["lanche","cafe"],
 [("pao_integral",50),("pasta_amendoim",25),("banana",80)],
 "Não precisa de geladeira e sustenta bem a tarde.",4),
("mk_sand_requeijao_peru","Sanduíche de queijo cremoso com peru",["lanche"],
 [("pao_integral",50),("requeijao",25),("peru",40),("rucula",20)],"Clássico do sanduíche natural.",5),
("mk_sand_ovo_pronto","Sanduíche de ovo com cenoura ralada",["lanche","cafe"],
 [("pao_integral",50),("ovo_pronto",100),("cenoura_crua",40)],
 "Use os ovos prontos embalados para não ter que cozinhar de manhã.",5),
("mk_sand_ricota_tomate","Sanduíche de ricota com tomate seco",["lanche"],
 [("pao_integral",50),("ricota",60),("tomate",50),("azeitona",15)],"Vegetariano e leve.",6),
("mk_sand_frango_pao_forma","Sanduíche de frango desfiado com queijo",["lanche","jantar"],
 [("pao_aveia",50),("frango_desfiado",70),("queijo_prato",25),("alface",20)],
 "Frango cozido no domingo rende a semana de sanduíches.",6),
("mk_sand_atum_grao","Sanduíche de atum com grão-de-bico amassado",["lanche","jantar"],
 [("pao_integral",50),("atum_sache",70),("grao_de_bico",60),("limao",8)],
 "O grão amassado substitui a maionese e ainda soma proteína.",8),
("mk_sand_presunto_ovo","Sanduíche de presunto com ovo",["lanche","cafe"],
 [("pao_frances",50),("presunto",35),("ovo_pronto",50),("tomate",35)],"Barato e proteico.",5),
("mk_wrap_frango_conserva","Wrap de frango em conserva com salada",["lanche","jantar"],
 [("pao_integral",60),("frango_conserva",80),("cenoura_crua",40),("rucula",25)],
 "Enrole apertado e corte ao meio.",7),
("mk_sand_queijo_goiabada","Sanduíche de queijo com goiaba",["lanche","ceia"],
 [("pao_sovado",50),("queijo_minas",45),("goiaba",100)],"Romeu e Julieta em versão de lanche.",4),

# ------------------------------------------- potes prontos de mercado
("mk_pote_grego_granola","Pote de iogurte grego com granola e banana-passa",["lanche","cafe"],
 [("iog_grego",200),("granola_pct",30),("banana_passa",25)],"Monte na véspera, granola por último.",4),
("mk_pote_proteico_uva","Iogurte proteico com uva-passa e castanha",["lanche","ceia"],
 [("iog_proteico",250),("uva_passa",25),("castanha_caju",15)],"Proteína alta e doce sem açúcar de mesa.",2),
("mk_atum_salada_pote","Pote de atum em sachê com grão-de-bico e tomate",["lanche","jantar","almoco"],
 [("atum_sache",80),("grao_de_bico",110),("tomate",70),("azeite",8)],
 "Marmita fria de 5 minutos, sem precisar esquentar.",8),
("mk_frango_conserva_pote","Pote de frango em conserva com milho e cenoura",["lanche","jantar"],
 [("frango_conserva",90),("milho_verde",70),("cenoura_crua",50),("azeite",6)],
 "Tudo de lata e de saco, montado na hora.",5),
]

# aguentam o dia inteiro fora da geladeira
MERCADO_SECO = {
 "mk_barra_fruta","mk_mix_frutas_secas","mk_chips_grao","mk_biscoito_pasta",
 "mk_banana_passa_castanha","mk_achoc_barra","mk_pasta_amendoim_banana",
 "mk_sand_pasta_amendoim","mk_whey_agua","mk_biscoito_queijo",
}
