# -*- coding: utf-8 -*-
# Mais opções de café da manhã e de lanche.
# ids "cf_" = feito em casa · "lv_" = dá para preparar antes e levar

CAFE_P = [
# ------------------------------------------------------- café da manhã
("cf_cuscuz_frango","Cuscuz com frango desfiado",["cafe","jantar"],
 [("cuscuz_milho",180),("frango_desfiado",80),("tomate",50)],
 "Cuscuz na cuscuzeira com o frango desfiado por cima, ainda quente.",18),
("cf_cuscuz_queijo_ovo","Cuscuz com queijo e ovo mexido",["cafe"],
 [("cuscuz_milho",170),("queijo_minas",40),("ovo_frito",55)],
 "Queijo por cima do cuscuz quente para derreter, ovo mexido ao lado.",18),
("cf_tapioca_frango","Tapioca recheada com frango e queijo cremoso",["cafe","jantar"],
 [("tapioca",40),("frango_desfiado",70),("requeijao",20)],
 "Recheie com o frango já temperado e uma colher de queijo cremoso.",10),
("cf_tapioca_ovo_queijo","Tapioca com ovo e queijo",["cafe"],
 [("tapioca",40),("ovo_frito",55),("queijo_minas",35)],
 "Espalhe a goma, quebre o ovo por cima e dobre quando firmar.",10),
("cf_pao_requeijao","Pão francês com queijo cremoso e café com leite",["cafe"],
 [("pao_frances",50),("requeijao",30),("leite",180)],
 "O café da manhã de padaria, em casa.",6),
("cf_pao_manteiga_mamao","Pão francês na chapa com mamão",["cafe"],
 [("pao_frances",50),("manteiga",10),("mamao",180)],
 "Pão aberto na frigideira com manteiga até dourar.",8),
("cf_pao_milho_queijo","Pão de milho com queijo minas",["cafe"],
 [("pao_milho",60),("queijo_minas",45),("laranja",130)],"Torre as fatias antes.",7),
("cf_pao_soja_amendoim","Pão de soja com pasta de amendoim e banana",["cafe","lanche"],
 [("pao_soja",50),("pasta_amendoim",20),("banana",80)],"Sacia por horas.",5),
("cf_mingau_tapioca","Mingau de tapioca com leite e canela",["cafe","ceia"],
 [("tapioca",40),("leite",220),("mel",10)],
 "Goma dissolvida no leite frio antes de levar ao fogo, senão empelota.",12),
("cf_mingau_fuba","Mingau de fubá",["cafe","ceia"],
 [("farinha_milho",45),("leite",220),("mel",10)],
 "Dissolva o fubá no leite ainda frio e mexa sem parar até engrossar.",15),
("cf_cara_ovo","Cará cozido com ovos",["cafe","lanche"],
 [("cara",170),("ovo_cozido",100)],"Cozinhe o cará na véspera; de manhã só esquentar.",20),
("cf_inhame_queijo","Inhame com queijo e café",["cafe"],
 [("inhame",170),("queijo_minas",40)],"Inhame cozido com casca sai fácil e sustenta bem.",22),
("cf_mandioca_ovo","Mandioca cozida com ovos mexidos",["cafe","jantar"],
 [("mandioca",170),("ovo_frito",90)],"Sobra de mandioca da véspera resolve o café da manhã.",20),
("cf_polenta_ovo","Polenta cremosa com ovo",["cafe","jantar"],
 [("polenta",170),("ovo_frito",60),("queijo_prato",20)],"Ovo pochê por cima da polenta mole.",20),
("cf_vitamina_abacate_aveia","Vitamina de abacate com aveia",["cafe","lanche"],
 [("abacate",90),("leite",220),("aveia",30)],"Cremosa e boa para quem treina cedo.",5),
("cf_acai_granola","Tigela de açaí com granola",["cafe","lanche"],
 [("acai",150),("granola_pct",35),("banana",70)],"Açaí sem xarope, adoçado só pela banana.",6),
("cf_suco_pao_queijo","Suco de laranja com pão e queijo",["cafe"],
 [("suco_laranja",250),("pao_integral",50),("queijo_minas",40)],"Simples e barato.",6),
("cf_iogurte_granola_mel","Iogurte com granola e mel",["cafe","lanche","ceia"],
 [("iogurte",170),("granola_pct",35),("mel",10)],"Granola por último para não amolecer.",3),
("cf_ovos_prato_tomate","Ovos mexidos com queijo prato e tomate",["cafe","jantar"],
 [("ovo_frito",110),("queijo_prato",25),("tomate",60),("pao_integral",40)],
 "Fogo baixo e mexer devagar deixa o ovo cremoso.",12),
("cf_omelete_espinafre_tomate","Omelete de espinafre e tomate",["cafe","jantar"],
 [("ovo_frito",100),("espinafre",70),("tomate",50)],"Escorra bem o espinafre refogado.",14),
("cf_panqueca_cacau","Panqueca de cacau com pasta de amendoim",["cafe","lanche"],
 [("aveia",45),("cacau",8),("ovo_frito",55),("banana",80),("pasta_amendoim",15)],
 "Massa batida no liquidificador, discos finos na frigideira.",18),
("cf_batata_doce_frango","Batata-doce com frango desfiado",["cafe","lanche","jantar"],
 [("batata_doce",160),("frango_desfiado",90)],"Café da manhã salgado de quem treina de manhã.",20),
("cf_torrada_abacate_codorna","Torrada com abacate e ovos de codorna",["cafe","lanche"],
 [("torrada",30),("abacate",70),("ovo_codorna",70),("limao",8)],
 "Abacate amassado com limão e sal, ovinhos cortados ao meio por cima.",10),
("cf_flocos_iogurte","Flocos de milho com iogurte e fruta",["cafe","lanche"],
 [("flocos_milho",40),("iogurte",150),("morango",80)],"Alternativa ao leite para quem prefere iogurte.",3),
("cf_leite_biscoito_arroz","Café com leite e biscoito de arroz",["cafe","ceia"],
 [("leite",220),("biscoito_arroz",30),("mel",8)],"Leve, para quem não tem fome de manhã.",4),

# ------------------------------------------------------------- lanches
("lv_grego_granola_mel","Iogurte grego com granola e mel",["lanche","ceia"],
 [("iog_grego",200),("granola_pct",30),("mel",10)],"Monte na hora de comer para a granola ficar crocante.",3),
("lv_vitamina_amendoim","Vitamina de banana com pasta de amendoim",["lanche","cafe"],
 [("leite",240),("banana",100),("pasta_amendoim",20)],"Bata bem e leve na garrafa.",4),
("lv_rolinho_queijo_tomate","Rolinhos de queijo prato com tomate",["lanche","ceia"],
 [("queijo_prato",45),("tomate",70)],"Enrole o tomate na fatia de queijo. Zero preparo.",3),
("lv_mamao_proteico","Mamão com iogurte proteico",["lanche","cafe","ceia"],
 [("mamao",160),("iog_proteico",200)],"Proteína alta e boa digestão.",3),
("lv_abacate_cacau_mel","Creme de abacate com cacau e mel",["lanche","ceia"],
 [("abacate",100),("cacau",8),("mel",10)],"Bata e leve gelado em pote.",5),
("lv_melancia_queijo","Melancia com queijo minas",["lanche","ceia"],
 [("melancia",220),("queijo_minas",45)],"Doce e salgado que funciona bem no calor.",4),
("lv_maracuja_biscoito","Suco de maracujá com biscoito de arroz",["lanche"],
 [("maracuja",70),("biscoito_arroz",30),("agua_coco",150)],"Bata o maracujá com a água de coco.",5),
("lv_palitos_homus","Palitos de cenoura e beterraba com homus",["lanche","ceia"],
 [("cenoura_crua",70),("beterraba",60),("grao_de_bico",90),("azeite",8)],
 "Homus em pote, palitos em saquinho. Aguenta o dia na bolsa térmica.",15),
("lv_milho_queijo","Milho verde com queijo ralado",["lanche","ceia"],
 [("milho_verde",130),("parmesao",12)],"Escorra bem e tempere na hora.",5),
("lv_pipoca_suco","Pipoca com suco integral",["lanche"],
 [("pipoca",28),("suco_cx",200)],"Pipoca estourada de manhã, em pote fechado.",10),
("lv_damasco_castanha","Damasco seco com castanhas",["lanche","ceia"],
 [("damasco",40),("castanha_caju",18)],"Não estraga e cabe no bolso.",1),
("lv_uva_passa_amendoim","Uva-passa com amendoim",["lanche","ceia"],
 [("uva_passa",30),("amendoim",25)],"O clássico mix de trilha, versão barata.",1),
("lv_kiwi_granola","Kiwi com granola",["lanche","ceia"],
 [("kiwi",140),("granola_pct",25)],"Leve a granola à parte.",3),
("lv_pessego_iogurte","Pêssego com iogurte natural",["lanche","ceia"],
 [("pessego",150),("iogurte",150)],"Fruta da estação sai bem mais barata.",3),
("lv_chips_agua_coco","Chips de grão-de-bico com água de coco",["lanche"],
 [("chips_grao",40),("agua_coco",250)],"Salgadinho proteico e hidratação.",1),
]

CAFE_SECO = {
 "lv_damasco_castanha","lv_uva_passa_amendoim","lv_pipoca_suco","lv_chips_agua_coco",
 "lv_maracuja_biscoito",
}
